### ISSUE TITLE
Make logos consistent

### ISSUE THREAD

**Issue by StrawHatHacker** [willpinha/daisy-collection#63]
### Description

Currently, "company logos" are not the daisy-collection logo in the footers folder

### Benefits

Consistency

### Implementation suggestions

 We can replace them with the daisy-collection logo

**Comment by willpinha** [comment]
You are right! Can you make a pull request fixing this issue?

**Comment by willpinha** [comment]
Hey @StrawHatHacker, I don't know if you know, but it is possible to work on multiple issues in the same fork (I just learned this, I'm still discovering ways to contribute to a repository). Just create a branch in your fork for each pull request you want to make, and make pull requests through these branches instead of master. This way you would have a branch in your fork for each pull request you want to make

If you already knew this, never mind, I'm still a noob on the subject 😅

**Comment by willpinha** [comment]
I will add this to the CONTRIBUTING guide

**Comment by StrawHatHacker** [comment]
Noted, I'll makenew pull requests
